apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns01-prod
spec:
  acme:
    email: assela@pathirana.net
    # Use the production ACME endpoint (staging is only for tests)
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Separate account key for production to avoid rate-limit collisions with staging
      name: letsencrypt-dns01-prod-account-key
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token
        selector:
          dnsZones:
            - "pathirana.net"
