apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-tls-cert
  namespace: monitoring
spec:
  secretName: grafana-tls-secret
  dnsNames:
    - grafana.monitor.k8s.pathirana.net
  issuerRef:
    name: letsencrypt-dns01-prod
    kind: ClusterIssuer
